apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: project1
  labels:
    author: moksh
spec:
  replicas: 3
  selector:
    matchLabels:
      type: webserver
  template:
    metadata:
      name: myprojectpod
      labels:
        type: webserver
    spec:
      containers:
      - name: p1
        image: sirmoksh/projectdeploy:5