apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myrs
  labels:
    author: moksh
spec:
  replicas: 3
  selector:
    matchLabels:
      type: webserver
  template:
    metadata:
      name: mypod
      labels:
        type: webserver
      spec:
        containers:
        - name: c1
          image: leaddevops/kubeserve:v2